/**
 * MediConnect Dataset - Comprehensive Mumbai Multi-Hospital & Clinic Network
 * Includes ALL 18+ Medical Specialties & 29+ Directory Doctors from verified Mumbai clinics
 */

export const INITIAL_DATA = {
  hospitals: [
    {
      id: "hosp-mumbai-1",
      name: "Lilavati Hospital & Research Centre",
      tagline: "Human Care Medical Services • 24/7 Tertiary Super Speciality",
      location: "A-791, Bandra Reclamation, Bandra West, Mumbai",
      city: "Mumbai",
      area: "Bandra West",
      distanceKm: 1.8,
      rating: 4.9,
      reviewCount: 1420,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2675 1000",
      status: "Approved",
      beds: {
        general: { available: 22, total: 120 },
        icu: { available: 5, total: 30 },
        emergency: { available: 8, total: 25 }
      },
      departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedic Specialist", "Pediatrician", "Gastroenterologist", "Gynecologist", "Nephrologist", "Pulmonologist"],
      badge: "NABH Accredited • Bandra",
      image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-2",
      name: "Kokilaben Dhirubhai Ambani Hospital",
      tagline: "World-Class Multi-Speciality Healthcare & Trauma Care",
      location: "Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai",
      city: "Mumbai",
      area: "Andheri West",
      distanceKm: 4.5,
      rating: 4.95,
      reviewCount: 2310,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 4269 6969",
      status: "Approved",
      beds: {
        general: { available: 45, total: 250 },
        icu: { available: 12, total: 60 },
        emergency: { available: 14, total: 40 }
      },
      departments: ["Cardiologist", "Neurologist", "Oncologist", "Pediatrician", "Orthopedic Specialist", "Pulmonologist", "Urologist", "Psychiatrist"],
      badge: "JCI & NABH • Andheri",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-3",
      name: "Breach Candy Hospital Trust",
      tagline: "Premier Healthcare & Cardiac Excellence in South Mumbai",
      location: "60-A, Bhulabhai Desai Road, Cumballa Hill, South Mumbai",
      city: "Mumbai",
      area: "South Mumbai",
      distanceKm: 8.2,
      rating: 4.85,
      reviewCount: 980,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2366 7788",
      status: "Approved",
      beds: {
        general: { available: 18, total: 90 },
        icu: { available: 4, total: 20 },
        emergency: { available: 6, total: 15 }
      },
      departments: ["General Physician", "Cardiologist", "Dermatologist", "Gynecologist", "Ophthalmologist", "Rheumatologist", "Dentist"],
      badge: "Heritage Excellence • South Mumbai",
      image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-4",
      name: "Fortis Hospital Mulund",
      tagline: "5-Time JCI Accredited Heart & Organ Transplant Institute",
      location: "Mulund Goregaon Link Road, Mulund West, Mumbai",
      city: "Mumbai",
      area: "Mulund West",
      distanceKm: 12.4,
      rating: 4.8,
      reviewCount: 1650,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 6799 4444",
      status: "Approved",
      beds: {
        general: { available: 32, total: 180 },
        icu: { available: 8, total: 45 },
        emergency: { available: 10, total: 30 }
      },
      departments: ["Cardiologist", "Nephrologist", "Orthopedic Specialist", "Pulmonologist", "Urologist", "Endocrinologist"],
      badge: "Transplant Hub • Mulund",
      image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-5",
      name: "Sir H. N. Reliance Foundation Hospital",
      tagline: "Advanced Robotic Surgery & Precision Healthcare",
      location: "Raja Rammohan Roy Road, Prarthana Samaj, Girgaon, South Mumbai",
      city: "Mumbai",
      area: "Girgaon",
      distanceKm: 7.6,
      rating: 4.9,
      reviewCount: 1890,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 6130 5000",
      status: "Approved",
      beds: {
        general: { available: 29, total: 150 },
        icu: { available: 7, total: 35 },
        emergency: { available: 9, total: 20 }
      },
      departments: ["General Physician", "Cardiologist", "Gastroenterologist", "ENT Specialist", "Oncologist", "Rheumatologist"],
      badge: "Robotic Center • Girgaon",
      image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-6",
      name: "Dr. L H Hiranandani Hospital",
      tagline: "Patient-Centric Multi-Speciality Center in Powai",
      location: "Hillside Road, Hiranandani Gardens, Powai, Mumbai",
      city: "Mumbai",
      area: "Powai",
      distanceKm: 9.1,
      rating: 4.75,
      reviewCount: 840,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2576 3300",
      status: "Approved",
      beds: {
        general: { available: 16, total: 80 },
        icu: { available: 3, total: 18 },
        emergency: { available: 5, total: 15 }
      },
      departments: ["Pediatrician", "Orthopedic Specialist", "ENT Specialist", "Ophthalmologist", "Dermatologist", "Dentist"],
      badge: "Green Hospital • Powai",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-7",
      name: "Nanavati Max Super Speciality Hospital",
      tagline: "350-Bed Iconic Medical Institution in Vile Parle",
      location: "SV Road, Near Mithibai College, Vile Parle West, Mumbai",
      city: "Mumbai",
      area: "Vile Parle West",
      distanceKm: 3.2,
      rating: 4.85,
      reviewCount: 1560,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2618 2255",
      status: "Approved",
      beds: {
        general: { available: 38, total: 200 },
        icu: { available: 9, total: 40 },
        emergency: { available: 11, total: 25 }
      },
      departments: ["General Physician", "Nephrologist", "Neurologist", "Cardiologist", "Gynecologist", "Psychiatrist"],
      badge: "Max Network • Vile Parle",
      image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-8",
      name: "Navi Mumbai & Raigad Medical Clinics Association",
      tagline: "Verified Primary & Specialist Care Centers in Belapur & Uran",
      location: "Sector-5 Market, CBD Belapur & Uran Dist. Raigad, Navi Mumbai",
      city: "Navi Mumbai",
      area: "Navi Mumbai",
      distanceKm: 14.2,
      rating: 4.7,
      reviewCount: 430,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 98181 52847",
      status: "Approved",
      beds: {
        general: { available: 15, total: 50 },
        icu: { available: 3, total: 10 },
        emergency: { available: 4, total: 10 }
      },
      departments: ["General Physician", "Pediatrician", "Family Medicine"],
      badge: "Verified Clinic • CBD Belapur & Uran",
      image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-9",
      name: "North Suburban Doctors Clinic Alliance",
      tagline: "Premier Family Clinics in Borivali, Kandivali & Dahisar",
      location: "L.T. Road Borivali West, Thakur Village Kandivali East & Dahisar West",
      city: "Mumbai",
      area: "Borivali / Kandivali",
      distanceKm: 8.5,
      rating: 4.8,
      reviewCount: 780,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2886 7141",
      status: "Approved",
      beds: {
        general: { available: 20, total: 60 },
        icu: { available: 4, total: 15 },
        emergency: { available: 5, total: 15 }
      },
      departments: ["General Physician", "Pediatrician", "Internal Medicine"],
      badge: "Suburban Hub • Borivali & Kandivali",
      image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-10",
      name: "Western Suburbs PolyClinic Network",
      tagline: "Multi-Speciality Clinics in Oshiwara, Goregaon, Khar & Malad",
      location: "New Link Rd Oshiwara, S.V. Road Goregaon West & Malad West",
      city: "Mumbai",
      area: "Goregaon / Jogeshwari",
      distanceKm: 5.4,
      rating: 4.75,
      reviewCount: 650,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2872 7553",
      status: "Approved",
      beds: {
        general: { available: 25, total: 70 },
        icu: { available: 5, total: 20 },
        emergency: { available: 6, total: 15 }
      },
      departments: ["General Physician", "Gynecologist", "Internal Medicine"],
      badge: "PolyClinic • Goregaon & Oshiwara",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-11",
      name: "Thane & Central Suburbs Doctor Network",
      tagline: "Polyclinics across Ghodbunder Road Thane & Vikhroli East",
      location: "Cosmos Regency Waghbil Thane West & Kannamwar Nagar Vikhroli East",
      city: "Mumbai",
      area: "Thane / Vikhroli",
      distanceKm: 11.0,
      rating: 4.7,
      reviewCount: 520,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2577 7803",
      status: "Approved",
      beds: {
        general: { available: 18, total: 55 },
        icu: { available: 3, total: 12 },
        emergency: { available: 4, total: 12 }
      },
      departments: ["General Physician", "Orthopedic Specialist", "Family Medicine"],
      badge: "Central Network • Thane & Vikhroli",
      image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-12",
      name: "South & Central Mumbai Clinic Network",
      tagline: "Verified Clinics in Dadar, Worli, Byculla, Bawalawadi, Bhendi Bazaar & Grant Road",
      location: "Behind Dadar Police Station, Worli Century Bazar, Byculla & Grant Rd, Mumbai",
      city: "Mumbai",
      area: "South Mumbai / Dadar",
      distanceKm: 6.8,
      rating: 4.82,
      reviewCount: 890,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2422 7281",
      status: "Approved",
      beds: {
        general: { available: 24, total: 80 },
        icu: { available: 6, total: 20 },
        emergency: { available: 7, total: 15 }
      },
      departments: ["General Physician", "Gynecologist", "Dermatologist", "Internal Medicine"],
      badge: "South & Central Hub • Dadar & Worli",
      image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "hosp-mumbai-13",
      name: "Mid-Suburbs & East Mumbai Doctors Association",
      tagline: "Family Healthcare Clinics in Santacruz, Ghatkopar, Chandivali & Versova",
      location: "Santacruz East, Rajawadi Ghatkopar East, Chandivali Powai & Versova Andheri",
      city: "Mumbai",
      area: "Santacruz / Ghatkopar",
      distanceKm: 5.1,
      rating: 4.78,
      reviewCount: 610,
      emergencyAvailable: true,
      ambulanceAvailable: true,
      ambulanceContact: "+91 22 2613 2181",
      status: "Approved",
      beds: {
        general: { available: 20, total: 65 },
        icu: { available: 4, total: 15 },
        emergency: { available: 5, total: 15 }
      },
      departments: ["General Physician", "Cardiologist", "Child Care"],
      badge: "Mid-Suburbs Hub • Santacruz & Ghatkopar",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80"
    }
  ],

  pendingHospitals: [
    {
      id: "hosp-p1",
      name: "Jupiter Hospital Thane",
      location: "Eastern Express Highway, Thane West, Mumbai MMR",
      appliedDate: "2026-09-04",
      contactPerson: "Dr. Ajay Kulkarni",
      phone: "+91 22 2172 5555",
      licenseNumber: "REG-MH-MUM-2026-881",
      departments: ["Pediatrician", "Cardiologist", "Orthopedic Specialist"],
      beds: { general: 40, icu: 15, emergency: 10 }
    }
  ],

  doctors: [
    // --- SCREENSHOT 1 DOCTORS ---
    {
      id: "doc-dir-1",
      hospitalId: "hosp-mumbai-8",
      name: "Dr. Anuradha Naik (Mrs.)",
      specialty: "General Physician",
      qualifications: "MBBS, General & Family Medicine Specialist",
      experience: "15 Years",
      fee: 500,
      rating: 4.8,
      status: "Available",
      area: "CBD Belapur",
      locationAddress: "Shop No. 21, Sector-5 Market, CBD-Belapur, Navi Mumbai",
      contactPhone: "9818152847",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:00 PM", "06:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-2",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. Archana A. Nanaware",
      specialty: "General Physician",
      qualifications: "MBBS, Family Healthcare Specialist",
      experience: "18 Years",
      fee: 600,
      rating: 4.85,
      status: "Available",
      area: "Kandivali East",
      locationAddress: "Shop No.50, Uranus, EMP III, Opp Dream Park, Thakur Village, Kandivali(E), Mumbai 400101",
      contactPhone: "022-28867141",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "11:30 AM", "12:00 PM", "06:30 PM", "07:30 PM", "08:30 PM"],
      bookedSlots: ["10:30 AM"]
    },
    {
      id: "doc-dir-3",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. Arva Shirazi (Mrs.)",
      specialty: "General Physician",
      qualifications: "MBBS, Child & General Health Practitioner",
      experience: "14 Years",
      fee: 550,
      rating: 4.75,
      status: "Available",
      area: "Borivali East",
      locationAddress: "Shop No. 12, Ashoka Tower, Opp. Raheja Estate, Kulupwadi Road, Borivali(E), Mumbai 400066",
      contactPhone: "9820742216",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:00 AM", "05:30 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-4",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. B. Girishchandra Alva",
      specialty: "General Physician",
      qualifications: "MBBS, Lachu Clinic Chief Physician",
      experience: "22 Years",
      fee: 650,
      rating: 4.9,
      status: "Available",
      area: "Borivali West",
      locationAddress: "Lachu Clinic, Jay-Raj Terrace, Vazira Naka, L.T. Road, Borivali (W), Mumbai 400091",
      contactPhone: "022-28990319 / 986903184",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:00 AM", "12:30 PM", "06:00 PM", "08:00 PM", "09:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-5",
      hospitalId: "hosp-mumbai-11",
      name: "Dr. Bavaskar C. Roopchand",
      specialty: "General Physician",
      qualifications: "MBBS, Diabetologist & General Consultant",
      experience: "20 Years",
      fee: 500,
      rating: 4.8,
      status: "Available",
      area: "Dombivli West",
      locationAddress: "Shop No 2 & 3A, Jai Om Mahadeo CHS, M P Rd, Dombivli West",
      contactPhone: "9820485279",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:00 AM", "11:00 AM", "12:30 PM", "06:00 PM", "08:00 PM", "09:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-6",
      hospitalId: "hosp-mumbai-10",
      name: "Dr. Bhajan K. Dhingreja",
      specialty: "General Physician",
      qualifications: "MD, Senior Consultant Physician",
      experience: "25 Years",
      fee: 800,
      rating: 4.92,
      status: "Available",
      area: "Khar West",
      locationAddress: "Shop No. 7, Ajanta Bldg., 3rd floor, Khar(W), Mumbai 400052",
      contactPhone: "9820011998",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "11:30 AM", "05:00 PM", "06:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-7",
      hospitalId: "hosp-mumbai-10",
      name: "Dr. Bharati S. Khade",
      specialty: "Gynecologist",
      qualifications: "MBBS, DGO, Obstetrics & Women's Health",
      experience: "19 Years",
      fee: 700,
      rating: 4.88,
      status: "Available",
      area: "Oshiwara / Jogeshwari",
      locationAddress: "302, Satpuda CHS, Oshiwara Park, Near Adarsh Nagar Signal, New Link Rd., Oshiwara, Jogeshwari (W) Mumbai 400102",
      contactPhone: "022-26743204 / 9322328594",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "04:30 PM", "06:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-8",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. Chandhrakala A.N.",
      specialty: "General Physician",
      qualifications: "MBBS, Ashwini Clinic Chief Doctor",
      experience: "16 Years",
      fee: 500,
      rating: 4.82,
      status: "Available",
      area: "Dahisar West",
      locationAddress: "Ashwini Clinic, 6, Matruchhaya, Gr. Floor, Laxman Mhatre Road, Navagaon, Dahisar (West), Mumbai 400068",
      contactPhone: "022-28941123",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "06:00 PM", "07:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-9",
      hospitalId: "hosp-mumbai-11",
      name: "Dr. Chetan S. Vaghela",
      specialty: "General Physician",
      qualifications: "MBBS, Family & General Health Specialist",
      experience: "15 Years",
      fee: 600,
      rating: 4.78,
      status: "Available",
      area: "Thane West",
      locationAddress: "Venus 3/3, Cosmos regency, Waghbil Rd, off G B Rd., Thane (W)",
      contactPhone: "9819881633",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "12:00 PM", "05:30 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-10",
      hospitalId: "hosp-mumbai-10",
      name: "Dr. Dattaram R. Koli",
      specialty: "General Physician",
      qualifications: "MBBS, Community Healthcare Doctor",
      experience: "17 Years",
      fee: 450,
      rating: 4.75,
      status: "Available",
      area: "Malad West",
      locationAddress: "Namdev Bhadari Chawl, Malwani Church, Marve Road, Malad (W), Mumbai 400095",
      contactPhone: "+91 98211 44556",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:00 AM", "05:00 PM", "06:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-11",
      hospitalId: "hosp-mumbai-8",
      name: "Dr. Devnikar B. Vithalbava",
      specialty: "General Physician",
      qualifications: "MBBS, General Medicine Practitioner",
      experience: "14 Years",
      fee: 450,
      rating: 4.7,
      status: "Available",
      area: "Uran Navi Mumbai",
      locationAddress: "Shop No.3, Shivam CHS, Karaanja Rd., Uran Dist. Raigad, Navi Mumbai",
      contactPhone: "9029368090",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:00 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-12",
      hospitalId: "hosp-mumbai-10",
      name: "Dr. Harish V. Dhuri",
      specialty: "General Physician",
      qualifications: "MBBS, Indira Clinic Senior Physician",
      experience: "21 Years",
      fee: 650,
      rating: 4.88,
      status: "Available",
      area: "Goregaon West",
      locationAddress: "Indira Clinic, Goregaon House, S.V. Road, Goregaon (W) Mumbai 400062",
      contactPhone: "022-28727553 / 9219541266",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:00 AM", "11:00 AM", "12:30 PM", "06:00 PM", "07:30 PM", "08:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-13",
      hospitalId: "hosp-mumbai-11",
      name: "Dr. Harishchandra M. Panchal",
      specialty: "General Physician",
      qualifications: "MBBS, Family Medicine Specialist",
      experience: "23 Years",
      fee: 550,
      rating: 4.84,
      status: "Available",
      area: "Vikhroli East",
      locationAddress: "10/148, Sumangal CHS, Kannamwar Nagar-1, Vikhroli(E), Mumbai 400083",
      contactPhone: "022-25777803",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:00 AM", "12:00 PM", "05:30 PM", "07:00 PM", "08:30 PM"],
      bookedSlots: []
    },

    // --- SCREENSHOT 2 DOCTORS ---
    {
      id: "doc-dir-14",
      hospitalId: "hosp-mumbai-11",
      name: "Dr. Jayshree H. Panchal (Mrs.)",
      specialty: "General Physician",
      qualifications: "MBBS, Family Healthcare Specialist",
      experience: "22 Years",
      fee: 550,
      rating: 4.85,
      status: "Available",
      area: "Vikhroli East",
      locationAddress: "10/148, Sumangal CHS, Kannamwar Nagar-1, Vikroli(E), Mumbai 400083",
      contactPhone: "022-25777803 / 9869041867",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:00 AM", "12:00 PM", "05:30 PM", "07:30 PM", "08:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-15",
      hospitalId: "hosp-mumbai-12",
      name: "Dr. Kamalakant S. Desai",
      specialty: "General Physician",
      qualifications: "MBBS, Dr. Desai Hospital Chief Doctor",
      experience: "26 Years",
      fee: 750,
      rating: 4.9,
      status: "Available",
      area: "Dadar West",
      locationAddress: "Dr.Desai Hospital, Baburao Parulekar Marg, Behind Dadar Police station,Dadar (W), Mumbai 400028",
      contactPhone: "022-24227281 / 9820622485",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:00 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-16",
      hospitalId: "hosp-mumbai-12",
      name: "Dr. Kiran Shah",
      specialty: "General Physician",
      qualifications: "MD, Senior Consultant Physician",
      experience: "20 Years",
      fee: 700,
      rating: 4.82,
      status: "Available",
      area: "Byculla / Bawalawadi",
      locationAddress: "8B, 9 Shri Dutta Krupa CHS, opp., Voltas, Dr.Ambedkar Rd.,Bawalawadi, Mumbai 400012",
      contactPhone: "022-23772330 / 9821392500",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["07:00 PM", "07:30 PM", "08:00 PM", "08:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-17",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. Kishor Kumar N Akoliya",
      specialty: "Pediatrician",
      qualifications: "MD (Pediatrics), Child Health Specialist",
      experience: "17 Years",
      fee: 650,
      rating: 4.86,
      status: "Available",
      area: "Kandivali East",
      locationAddress: "D/703, Marigold, Valley of Flowers, Nr Evershin's Dreams Park, Thakur Village, Kandivali(E), Mumbai 400101",
      contactPhone: "022-28463783 / 9819548714",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:30 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-18",
      hospitalId: "hosp-mumbai-13",
      name: "Dr. Krishnaji Dattatraya Dabholkar",
      specialty: "General Physician",
      qualifications: "MD (General Medicine), Internal Medicine Practitioner",
      experience: "24 Years",
      fee: 700,
      rating: 4.88,
      status: "Available",
      area: "Santacruz East",
      locationAddress: "1/2, Sanket, Vakola Police Station Rd., Anand Nagar, Santacruz (E), Mumbai 400055",
      contactPhone: "022-26132181 / 9869086530",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "11:30 AM", "12:30 PM", "06:30 PM", "08:00 PM", "09:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-19",
      hospitalId: "hosp-mumbai-12",
      name: "Dr. Krupa M Tome",
      specialty: "Gynecologist",
      qualifications: "MBBS, DGO, Parikh Nursing Home Consultant",
      experience: "15 Years",
      fee: 800,
      rating: 4.84,
      status: "Available",
      area: "Worli",
      locationAddress: "Parikh Nursing Home, Opp. Century Bazar, Worli, Mumbai 400025",
      contactPhone: "9004226215 / 9619069160",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-20",
      hospitalId: "hosp-mumbai-10",
      name: "Dr. Manjiri Kawde",
      specialty: "Dermatologist",
      qualifications: "MD (Dermatology), Chrysalizz Clinic Director",
      experience: "18 Years",
      fee: 900,
      rating: 4.9,
      status: "Available",
      area: "Khar West",
      locationAddress: "Chrysalizz, 18th Road, Khar (W), Mumbai 400052",
      contactPhone: "022-26496239 / 9821055866",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["08:00 AM", "10:00 AM", "12:00 PM", "06:00 PM", "07:30 PM", "08:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-21",
      hospitalId: "hosp-mumbai-11",
      name: "Dr. Manjit Pradhan",
      specialty: "General Physician",
      qualifications: "MBBS, Orthopedic & Family Health Consultant",
      experience: "16 Years",
      fee: 600,
      rating: 4.78,
      status: "Available",
      area: "Thane West",
      locationAddress: "Bldg. No. 8, B-11, Shopping Centre, Devdaya CHS, Phase 1, Near Shastri Nagar, Thane",
      contactPhone: "9819520710",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:00 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-22",
      hospitalId: "hosp-mumbai-13",
      name: "Dr. Milan Sheth",
      specialty: "Cardiologist",
      qualifications: "MD, DM (Cardiology), Rajawadi Specialist",
      experience: "21 Years",
      fee: 1000,
      rating: 4.89,
      status: "Available",
      area: "Ghatkopar East",
      locationAddress: "18 Ground Flr, Savani Apts, Rajawadi, Ghatkopar(E), Mumbai 400077",
      contactPhone: "022-21027612 / 9930969109",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "11:30 AM", "04:30 PM", "06:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-23",
      hospitalId: "hosp-mumbai-13",
      name: "Dr. Mohandas Shetty",
      specialty: "General Physician",
      qualifications: "MBBS, Family Medicine Practitioner",
      experience: "19 Years",
      fee: 550,
      rating: 4.8,
      status: "Available",
      area: "Chandivali / Powai",
      locationAddress: "24/C/004, Sai Sadan, Chandivali, Mumbai 400072",
      contactPhone: "022-28475375",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:00 AM", "05:30 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-24",
      hospitalId: "hosp-mumbai-13",
      name: "Dr. Nandkishore R Ramle",
      specialty: "General Physician",
      qualifications: "MBBS, Versova Village Doctor",
      experience: "17 Years",
      fee: 500,
      rating: 4.75,
      status: "Available",
      area: "Versova Andheri",
      locationAddress: "Malu Govind Niwas, P Ramle Marg, Dongarigally, Versova Village, Andheri (W), Mumbai",
      contactPhone: "9969722720",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:00 PM", "06:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-25",
      hospitalId: "hosp-mumbai-12",
      name: "Dr. Naseeruddin Z A Khan",
      specialty: "General Physician",
      qualifications: "MBBS, As-Shifa Clinic Chief Physician",
      experience: "23 Years",
      fee: 500,
      rating: 4.85,
      status: "Available",
      area: "Bhendi Bazaar / South Mumbai",
      locationAddress: "As-Shifa Clinic, 184/192, Jama Masjid Trust Bldg, Nishanpada Rd, Mumbai 400009",
      contactPhone: "022-9821844336 / 9867089033",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "06:00 PM", "08:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-26",
      hospitalId: "hosp-mumbai-10",
      name: "Dr. Nasreen R Shaikh",
      specialty: "General Physician",
      qualifications: "MBBS, Al-Shifa Clinic Women & General Physician",
      experience: "15 Years",
      fee: 550,
      rating: 4.8,
      status: "Available",
      area: "Andheri West",
      locationAddress: "Al-Shifa Clinic, Shop No.2, Next to Oscar Public School, Gaon Devi Dongri, Andheri (W), Mumbai",
      contactPhone: "9819948846",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "12:00 PM", "05:30 PM", "07:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-27",
      hospitalId: "hosp-mumbai-12",
      name: "Dr. Nayak Shivanand Manjunath",
      specialty: "General Physician",
      qualifications: "MD (General Medicine), Internal Medicine Practitioner",
      experience: "25 Years",
      fee: 700,
      rating: 4.9,
      status: "Available",
      area: "Grant Road / South Mumbai",
      locationAddress: "3, Shantiniketan, 11 Padamji Rd.,off Pavwalla Street, Mumbai 400004",
      contactPhone: "022-23864060 / 9969363840",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "12:30 PM", "06:00 PM", "08:00 PM", "09:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-28",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. Neela Chokshi",
      specialty: "General Physician",
      qualifications: "MBBS, Namit Clinic Family Doctor",
      experience: "20 Years",
      fee: 600,
      rating: 4.82,
      status: "Available",
      area: "Kandivali East",
      locationAddress: "Namit Clinic, Anant Apt., Near Suruchi Hotel, Kandivali(E), Mumbai 400101",
      contactPhone: "022-28864000 / 9820123456",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "05:00 PM", "06:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-dir-29",
      hospitalId: "hosp-mumbai-9",
      name: "Dr. Nitin P Sangani",
      specialty: "General Physician",
      qualifications: "MD, Diabetologist & Senior Physician",
      experience: "27 Years",
      fee: 750,
      rating: 4.92,
      status: "Available",
      area: "Kandivali West",
      locationAddress: "A/2 Nilkanth, Fateh Baug, S V Rd, Opp Police Stn., Kandivali(W), Mumbai 400067",
      contactPhone: "022-28066755 / 9892484684",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:00 AM", "11:00 AM", "12:30 PM", "07:00 PM", "08:30 PM", "09:30 PM"],
      bookedSlots: []
    },

    // --- PREMIER HOSPITAL SUPER SPECIALISTS ---
    {
      id: "doc-mumbai-1",
      hospitalId: "hosp-mumbai-1",
      name: "Dr. Shashank Joshi",
      specialty: "General Physician",
      qualifications: "MD, DM (Endocrinology), FACP, FRCP (London)",
      experience: "24 Years",
      fee: 800,
      rating: 4.95,
      status: "Available",
      area: "Bandra West",
      locationAddress: "Lilavati Hospital, Bandra Reclamation, Bandra West, Mumbai",
      contactPhone: "+91 22 2675 1000",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "10:00 AM", "10:30 AM", "11:30 AM", "02:00 PM"],
      bookedSlots: ["10:00 AM"]
    },
    {
      id: "doc-mumbai-2",
      hospitalId: "hosp-mumbai-1",
      name: "Dr. Ashwin Mehta",
      specialty: "Cardiologist",
      qualifications: "MD, DM (Cardiology), FACC, Director of Cardiology",
      experience: "28 Years",
      fee: 1500,
      rating: 4.98,
      status: "Available",
      area: "Bandra West",
      locationAddress: "Lilavati Hospital, Bandra Reclamation, Bandra West, Mumbai",
      contactPhone: "+91 22 2675 1000",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:00 AM", "03:00 PM", "04:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-6",
      hospitalId: "hosp-mumbai-3",
      name: "Dr. Rashmi Sarkar",
      specialty: "Dermatologist",
      qualifications: "MD (Dermatology), DVD, MNAMS",
      experience: "16 Years",
      fee: 900,
      rating: 4.85,
      status: "Available",
      area: "South Mumbai",
      locationAddress: "Breach Candy Hospital, Bhulabhai Desai Road, South Mumbai",
      contactPhone: "+91 22 2366 7788",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["11:00 AM", "11:30 AM", "02:00 PM", "03:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-9",
      hospitalId: "hosp-mumbai-6",
      name: "Dr. Nimish Shah",
      specialty: "Pediatrician",
      qualifications: "MD (Pediatrics), DCH (Mumbai)",
      experience: "14 Years",
      fee: 750,
      rating: 4.85,
      status: "Available",
      area: "Powai",
      locationAddress: "Dr. L H Hiranandani Hospital, Powai, Mumbai",
      contactPhone: "+91 22 2576 3300",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:00 AM", "04:00 PM", "05:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-4",
      hospitalId: "hosp-mumbai-2",
      name: "Dr. Santosh Shetty",
      specialty: "Orthopedic Specialist",
      qualifications: "MS (Orthopedics), MCh, Joint Replacement Pioneer",
      experience: "19 Years",
      fee: 1200,
      rating: 4.9,
      status: "Available",
      area: "Andheri West",
      locationAddress: "Kokilaben Hospital, Four Bungalows, Andheri West, Mumbai",
      contactPhone: "+91 22 4269 6969",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "10:30 AM", "11:00 AM", "03:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-11",
      hospitalId: "hosp-mumbai-1",
      name: "Dr. Sangeeta Rawat",
      specialty: "Neurologist",
      qualifications: "DM (Neurology), MD (General Medicine)",
      experience: "21 Years",
      fee: 1300,
      rating: 4.91,
      status: "Available",
      area: "Bandra West",
      locationAddress: "Lilavati Hospital, Bandra Reclamation, Bandra West, Mumbai",
      contactPhone: "+91 22 2675 1000",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "11:30 AM", "03:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-10",
      hospitalId: "hosp-mumbai-7",
      name: "Dr. Hemant Deshmukh",
      specialty: "Gastroenterologist",
      qualifications: "MD, DM (Gastroenterology), KEM Alumnus",
      experience: "22 Years",
      fee: 1100,
      rating: 4.9,
      status: "Available",
      area: "Vile Parle West",
      locationAddress: "Nanavati Max Hospital, SV Road, Vile Parle West, Mumbai",
      contactPhone: "+91 22 2618 2255",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "10:30 AM", "12:00 PM", "03:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-12",
      hospitalId: "hosp-mumbai-6",
      name: "Dr. Keiki Mehta",
      specialty: "Ophthalmologist",
      qualifications: "MS (Ophthalmology), DO, Cataract & LASIK Specialist",
      experience: "26 Years",
      fee: 1000,
      rating: 4.94,
      status: "Available",
      area: "Powai",
      locationAddress: "Dr. L H Hiranandani Hospital, Powai, Mumbai",
      contactPhone: "+91 22 2576 3300",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "02:30 PM", "04:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-13",
      hospitalId: "hosp-mumbai-5",
      name: "Dr. Milind Kirtane",
      specialty: "ENT Specialist",
      qualifications: "MS (ENT), DORL, Padma Shri Cochlear Implant Pioneer",
      experience: "32 Years",
      fee: 1600,
      rating: 4.98,
      status: "Available",
      area: "Girgaon",
      locationAddress: "Sir H. N. Reliance Foundation Hospital, Girgaon, South Mumbai",
      contactPhone: "+91 22 6130 5000",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["11:00 AM", "12:00 PM", "03:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-14",
      hospitalId: "hosp-mumbai-2",
      name: "Dr. Suresh Advani",
      specialty: "Oncologist",
      qualifications: "DM (Oncology), Padma Bhushan Medical Oncologist",
      experience: "34 Years",
      fee: 2000,
      rating: 5.0,
      status: "Available",
      area: "Andheri West",
      locationAddress: "Kokilaben Hospital, Four Bungalows, Andheri West, Mumbai",
      contactPhone: "+91 22 4269 6969",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "02:00 PM", "04:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-15",
      hospitalId: "hosp-mumbai-3",
      name: "Dr. Rishma Pai",
      specialty: "Gynecologist",
      qualifications: "MD, DGO, FCPS, FICOG, IVF Specialist",
      experience: "25 Years",
      fee: 1200,
      rating: 4.93,
      status: "Available",
      area: "South Mumbai",
      locationAddress: "Breach Candy Hospital, Bhulabhai Desai Road, South Mumbai",
      contactPhone: "+91 22 2366 7788",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "11:30 AM", "02:30 PM", "04:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-16",
      hospitalId: "hosp-mumbai-4",
      name: "Dr. Bharat Shah",
      specialty: "Nephrologist",
      qualifications: "MD, DM (Nephrology), Renal Transplant Expert",
      experience: "27 Years",
      fee: 1400,
      rating: 4.92,
      status: "Available",
      area: "Mulund West",
      locationAddress: "Fortis Hospital, Mulund West, Mumbai",
      contactPhone: "+91 22 6799 4444",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:00 AM", "03:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-17",
      hospitalId: "hosp-mumbai-4",
      name: "Dr. Zarir Udwadia",
      specialty: "Pulmonologist",
      qualifications: "MD, DNB, FCCP (USA), FRCP (London)",
      experience: "29 Years",
      fee: 1800,
      rating: 4.97,
      status: "Available",
      area: "Mulund West",
      locationAddress: "Fortis Hospital, Mulund West, Mumbai",
      contactPhone: "+91 22 6799 4444",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "12:00 PM", "03:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-18",
      hospitalId: "hosp-mumbai-7",
      name: "Dr. Harish Shetty",
      specialty: "Psychiatrist",
      qualifications: "MD (Psychiatry), DPM, Mental Health Counselor",
      experience: "23 Years",
      fee: 1200,
      rating: 4.89,
      status: "Available",
      area: "Vile Parle West",
      locationAddress: "Nanavati Max Hospital, SV Road, Vile Parle West, Mumbai",
      contactPhone: "+91 22 2618 2255",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["11:00 AM", "02:00 PM", "04:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-19",
      hospitalId: "hosp-mumbai-2",
      name: "Dr. T. B. Yuvaraja",
      specialty: "Urologist",
      qualifications: "MCh (Urology), Robotic Uro-Onco Surgeon",
      experience: "20 Years",
      fee: 1500,
      rating: 4.91,
      status: "Available",
      area: "Andheri West",
      locationAddress: "Kokilaben Hospital, Four Bungalows, Andheri West, Mumbai",
      contactPhone: "+91 22 4269 6969",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:30 AM", "01:30 PM", "04:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-20",
      hospitalId: "hosp-mumbai-4",
      name: "Dr. Manoj Chadha",
      specialty: "Endocrinologist",
      qualifications: "MD, DM (Endocrinology), Diabetes Specialist",
      experience: "22 Years",
      fee: 1100,
      rating: 4.88,
      status: "Available",
      area: "Mulund West",
      locationAddress: "Fortis Hospital, Mulund West, Mumbai",
      contactPhone: "+91 22 6799 4444",
      image: "https://images.unsplash.com/photo-1594824813566-78a1ed6a2b43?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["09:30 AM", "11:30 AM", "03:00 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-21",
      hospitalId: "hosp-mumbai-5",
      name: "Dr. Rohini Handa",
      specialty: "Rheumatologist",
      qualifications: "MD, DNB, FAMS, Autoimmune Disease Specialist",
      experience: "26 Years",
      fee: 1300,
      rating: 4.9,
      status: "Available",
      area: "Girgaon",
      locationAddress: "Sir H. N. Reliance Foundation Hospital, Girgaon, South Mumbai",
      contactPhone: "+91 22 6130 5000",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:30 AM", "02:30 PM"],
      bookedSlots: []
    },
    {
      id: "doc-mumbai-22",
      hospitalId: "hosp-mumbai-3",
      name: "Dr. Sandesh Mayekar",
      specialty: "Dentist",
      qualifications: "MDS (Prosthodontics), Aesthetic Dentistry Pioneer",
      experience: "28 Years",
      fee: 850,
      rating: 4.92,
      status: "Available",
      area: "South Mumbai",
      locationAddress: "Breach Candy Hospital, Bhulabhai Desai Road, South Mumbai",
      contactPhone: "+91 22 2366 7788",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
      availableSlots: ["10:00 AM", "11:00 AM", "03:00 PM", "04:30 PM"],
      bookedSlots: []
    }
  ],

  // Symptom Mapping Engine
  symptomKnowledgeBase: [
    {
      symptoms: ["fever", "headache", "body pain", "fatigue", "chills", "weakness", "viral"],
      specialist: "General Physician",
      urgency: "Moderate",
      advice: "Recommended for viral fevers, seasonal flu, Dengue/Malaria screening & general illness."
    },
    {
      symptoms: ["chest pain", "breathlessness", "palpitations", "left arm pain", "dizziness", "heart"],
      specialist: "Cardiologist",
      urgency: "High / Emergency",
      advice: "Requires immediate cardiovascular evaluation at Mumbai's top cardiac emergency units."
    },
    {
      symptoms: ["joint pain", "back pain", "bone fracture", "knee pain", "stiffness", "ortho"],
      specialist: "Orthopedic Specialist",
      urgency: "Moderate",
      advice: "Recommended for bone fractures, arthritis, joint replacements, tendon injuries."
    },
    {
      symptoms: ["skin rash", "itching", "acne", "hair loss", "skin redness", "allergies"],
      specialist: "Dermatologist",
      urgency: "Low",
      advice: "Recommended for skin allergies, fungal infections, eczema, and dermatological care."
    },
    {
      symptoms: ["stomach ache", "acidity", "indigestion", "nausea", "vomiting", "diarrhea"],
      specialist: "Gastroenterologist",
      urgency: "Moderate",
      advice: "Recommended for stomach infections, acidity, GERD, and liver wellness."
    },
    {
      symptoms: ["child fever", "infant cough", "pediatric growth issue", "vaccination"],
      specialist: "Pediatrician",
      urgency: "Moderate",
      advice: "Recommended for infant, child, and adolescent pediatric healthcare."
    }
  ],

  appointments: [
    {
      id: "apt-mum-101",
      tokenNo: "A-18",
      patientName: "Karan Johar",
      patientPhone: "+91 98200 99887",
      patientAge: 45,
      patientGender: "Male",
      hospitalId: "hosp-mumbai-1",
      hospitalName: "Lilavati Hospital & Research Centre",
      doctorId: "doc-mumbai-1",
      doctorName: "Dr. Shashank Joshi",
      specialty: "General Physician",
      date: "2026-09-05",
      timeSlot: "10:00 AM",
      symptom: "Fever + Headache + Body Pain",
      type: "Regular",
      fee: 800,
      status: "In-Consultation",
      createdAt: "2026-09-05 09:15 AM"
    }
  ],

  queueState: {
    "doc-mumbai-1": {
      currentlyServingToken: "A-18",
      nextToken: "A-19",
      totalInQueue: 4,
      avgConsultationMin: 12
    }
  }
};
